site_name: Competitive Programming
theme:
  name: material
  language: sr
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list

nav:
  - Home: index.md
  - Problems Archive: problems/
  - Source Code: src/
