site_name: Моја такмичења
theme:
  name: material
  language: sr
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list

# Ово говори MkDocs-у да занемари чињеницу да фајлови нису у docs
docs_dir: .
# Ово спречава да се на сајту појаве системски Гит фајлови
exclude_docs: |
  .github/
  .git/
  mkdocs.yml
  site/
  publish.yml

nav:
  - Почетна: docs/index.md
  - Код (Source): 
      - src/
