site_name: Моја такмичења
theme:
  name: material
  language: sr
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list

nav:
  - Почетна: index.md
  - Код (Source): 
      - src/

